---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-example-com
  namespace: echo
  annotations:
    konghq.com/plugins: request-id
spec:
  ingressClassName: default
  rules:
  - host: example.com
    http:
      paths:
      - path: /bar
        pathType: ImplementationSpecific
        backend:
          service:
            host: example.com
            name: echo
            port:
              number: 80